# Default values for Maven projects.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: docker-registry.default.svc:5000/entando/entando-jx-maven-java11
  tag: 0.0.12
  pullPolicy: IfNotPresent
