# Default values for Maven projects.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: https://index.docker.io/v1//entando-k8s-infrastructure/entando-jx-maven-java11
  tag: 0.0.29
  pullPolicy: IfNotPresent
